#!/bin/sh
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.

## constants
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
__root_dir="$(cd "${__dir}/.." && pwd -P)"

## env variables
export DOTFILES=$HOME/.dotfiles

## set flags
# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Catch the error in case pipe fails
set -o pipefail
# Turn on traces, useful while debugging but commented out by default
[[ "${DEBUG}" = true ]] && set -o xtrace


usage() {
	echo "dot -- dotfiles management"
	echo ""
	echo "Usage: dot [options]"
	echo ""
	echo "Options:"
	echo "  -e, --edit    Open dotfiles directory for editing"
	echo "  -h, --help    Show this help message and exit"
	exit
}

while test $# -gt 0; do
	case "$1" in
		"-h"|"--help")
			usage
			;;
		"-e"|"--edit")
			exec "$EDITOR" "${DOTFILES}"
			exit
			;;
		*)
			echo "Invalid option: $1"
			usage
			;;
	esac
	shift
done

# Install homebrew
$DOTFILES/homebrew/install.sh 2>&1

# Upgrade homebrew
echo "› brew update"
brew update

# Install software
echo "› $DOTFILES/script/install"
$DOTFILES/script/install
