#!/bin/sh
##
# DESCRIPTION:
#
# Script to be used as commit hook that will extract ticket number from the branch name
# and add it to the end of your commit msg. The script expects the JIRA ticket to follow
# the format of PROJECTSYMBOL-TICKETNUMBER.
#
# For example, after adding this to your commit-hooks you can create branchs with names 
# like:
#
# ```
# git checkout -b WEAV-1234-some-description
# ````
# 
# and the script will add WEAV-1234 to end of your commit messages.

## flags
# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Catch the error in case pipe fails
set -o pipefail
# Turn on traces, turn own by adding DEBUG=true to environment variables
[[ "${DEBUG}" = true ]] && set -o xtrace

## functions
get_current_branch_name() {
    git symbolic-ref HEAD | sed 's!refs\/heads\/!!'
}
info() {
    printf "  [\033[00;34mINFO\033[0m] $1\n"
}
warn() {
    printf "  [\033[00;33mWARN\033[0m] $1\n"
}

extract_jira_ticket() {
    echo $1 | grep -E '[A-Z]{4,}-[0-9]+' -o | head -n1 || echo ""
}

## main
# extract jira ticket from commit message
branch_name="$(get_current_branch_name)"

# if we are in master/main, just exit as we won't have a ticket number
[ "$branch_name" == "master" ] || [ "$branch_name" == "main" ] && exit 0

message="$(cat $1 | grep -v '^#')"
ticket=$(extract_jira_ticket "$message")

# if no jira ticket number was found
if [ -z "$ticket" ];
  then
    # try to extract jira ticket number from branch name
    ticket="$(extract_jira_ticket "$branch_name")"

    if [ ! ${message:0:1} == "\n" ]
    then
        if [ -n "$ticket" ]
        # add if there is a ticket number on the branch, just add it to the commit msg
        then
            info "Adding ticket number '\033[0;36m$ticket\033[0m' to commit message: "
            echo "$message\n\n$ticket\n" > "$1"
        else
            warn "No ticket number was found to be added to commit message!"
            warn "Remember to either add it by yourself or create the branch using the ticket number."
            warn "Example: \033[0;32mgit checkout -b WEAV-1235-branch-with-jira-ticket-number\033[0m\n"
        fi
    fi
  else
    info "Ticket number '\033[0;36m$ticket\033[0m' was already added to commit message"
fi
